// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/21/2025, 11:38:03 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/hp/Documents/JABUSPARK-MVP/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hp/Documents/JABUSPARK-MVP/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hp/Documents/JABUSPARK-MVP/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hp/Documents/JABUSPARK-MVP/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hp/Documents/JABUSPARK-MVP/plugins/**/*.{js,ts,mjs}","C:/Users/hp/Documents/JABUSPARK-MVP/composables/**/*.{js,ts,mjs}","C:/Users/hp/Documents/JABUSPARK-MVP/utils/**/*.{js,ts,mjs}","C:/Users/hp/Documents/JABUSPARK-MVP/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hp/Documents/JABUSPARK-MVP/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hp/Documents/JABUSPARK-MVP/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hp/Documents/JABUSPARK-MVP/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;