// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/20/2025, 9:36:31 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/hp/Downloads/JabuSpark/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hp/Downloads/JabuSpark/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hp/Downloads/JabuSpark/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hp/Downloads/JabuSpark/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hp/Downloads/JabuSpark/plugins/**/*.{js,ts,mjs}","C:/Users/hp/Downloads/JabuSpark/composables/**/*.{js,ts,mjs}","C:/Users/hp/Downloads/JabuSpark/utils/**/*.{js,ts,mjs}","C:/Users/hp/Downloads/JabuSpark/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hp/Downloads/JabuSpark/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hp/Downloads/JabuSpark/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hp/Downloads/JabuSpark/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;