// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/18/2025, 9:35:54 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/sam/jabuspark-mvp/apps/web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sam/jabuspark-mvp/apps/web/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sam/jabuspark-mvp/apps/web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sam/jabuspark-mvp/apps/web/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sam/jabuspark-mvp/apps/web/plugins/**/*.{js,ts,mjs}","C:/Users/sam/jabuspark-mvp/apps/web/composables/**/*.{js,ts,mjs}","C:/Users/sam/jabuspark-mvp/apps/web/utils/**/*.{js,ts,mjs}","C:/Users/sam/jabuspark-mvp/apps/web/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sam/jabuspark-mvp/apps/web/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sam/jabuspark-mvp/apps/web/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sam/jabuspark-mvp/apps/web/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;